config/routes.rb
Rails.application.routes.draw do

 
  resources :users, only: %i[new create]
  resources :tags do
    get :autocomplete_tag_title, :on => :collection
  end
  resources :ad_posts 
  get 'signup'=> 'users#new'
  get '/tags', to: 'tags#index'
  get '/ad_posts', to: 'ad_post#index' 
 root 'ad_posts#index'


end

app/models/ad_post.rb
class AdPost < ApplicationRecord
    has_and_belongs_to_many :tags
    accepts_nested_attributes_for :tags
    has_many_attached :images
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_and_belongs_to_many :ad_posts
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase } 
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true,format: { with: VALID_EMAIL_REGEX}
    validates :name, presence: true
    has_secure_password
    validates :password, presence: true
end
 

app/controllers/ad_posts_controller.rb
class AdPostsController < ApplicationController
  before_action :set_ad_post, only: %i[ show edit update destroy ]
  
  # GET /ad_posts or /ad_posts.json
  def index  
    
    @ad_posts = AdPost.all
    @pagy, @ad_posts = pagy @ad_posts

  end

  # GET /ad_posts/1 or /ad_posts/1.json
  def show
    @ad_posts= AdPost.includes(:tags).find(params[:id])
    @tags = @ad_posts.tags
  end

  # GET /ad_posts/new
  def new

    @ad_post = AdPost.new
    @tags = Tag.all
  

  end

  # GET /ad_posts/1/edit
  def edit
    @tags = Tag.all 

    
  end

  # POST /ad_posts or /ad_posts.json
  def create 
    
    @temp_params = ad_post_params
    
    # @tags = Tag.all
    # @temp_params[:tags] = @temp_params[:tags].map{ |tag_id| @tags.find (tag_id)}
    @temp_params[:tags] = params[:ad_post][:tags].split(",").reject(&:empty?).map{ |tag_title| Tag.find_by(title: tag_title)}

    @ad_post_images_names = []

    @temp_params[:images].each do |file|
        @returned_hash = Cloudinary::Uploader.upload(file, options = {})
        @ad_post_images_names.push( @returned_hash["public_id"] )

    end 

    @temp_params[:images_filename] = @ad_post_images_names  
    

    @ad_post = AdPost.new(@temp_params)
    

    
   

    respond_to do |format|
      if @ad_post.save
        format.html { redirect_to @ad_post, notice: "Ad post was successfully created." }
        format.json { render :show, status: :created, location: @ad_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ad_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ad_posts/1 or /ad_posts/1.json
  def update
    @tags = Tag.all
    @temp_params = ad_post_params
    @temp_params[:tags] = @temp_params[:tags].map{ |tag_id| @tags.find (tag_id)}

    

    respond_to do |format|
      if @ad_post.update(@temp_params)

        format.html { redirect_to @ad_post, notice: "Ad post was successfully updated." }
        format.json { render :show, status: :ok, location: @ad_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ad_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ad_posts/1 or /ad_posts/1.json
  def destroy
    @ad_post.destroy
    respond_to do |format|
      format.html { redirect_to ad_posts_url, notice: "Ad post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad_post
      @ad_post = AdPost.includes(:tags).find(params[:id])
      

    end

    # Only allow a list of trusted parameters through.
    def ad_post_params
      params.require(:ad_post).permit(:title, :description, { tags: [] }, images: [])
    end

   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
    
    private

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
    end

    def user_signed_in?
        current_user.present?
    end


    helper_method :current_user, :user_signed_in?
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[ show edit update destroy ] 
  autocomplete :tag, :title
  

  # GET /tags or /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1 or /tags/1.json
  def show

  end

  # GET /tags/new
  def new   
    @tag = Tag.new
    

   
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags or /tags.json
  def create
    @tag = Tag.new(tag_params)
 
    respond_to do |format|
      if @tag.save  
        format.html { redirect_to @tag, notice: "Tag was successfully created." }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1 or /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: "Tag was successfully updated." }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1 or /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: "Tag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tag_params
      params.require(:tag).permit(:title,:tags)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/"
    else
      render :new
    end

  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
autocomplete :tags, :title

class WelcomeController < ApplicationController
  def show
  end
end

app/helpers/ad_posts_helper.rb
module AdPostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/main_page_helper.rb
module MainPageHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ad_posts/_form.html.slim
= form_with(model: @ad_post) do |form|
  - if @ad_post.errors.any?
    #error_explanation
      h2
        = pluralize(ad_post.errors.count, "error")
        | prohibited this ad_post from being saved:
      ul
        - ad_post.errors.each do |error|
          li= error.full_message

  .field
    = form.label :title
  .field
    = form.text_field :title, required: true, placeholder: "Enter a title ad"
  .field
    = form.label :description
  .field
    = form.text_field :description, required: true, minlength: 6, placeholder:"Enter a description ad"

  / - @tags.each do |tag|
  /   .field 
  /     = form.label tag.title 
  /     = form.check_box :tags, {multiple: true, checked: }, tag.id, false //
    
  .field 
    = form.autocomplete_field :tags, autocomplete_tag_title_tags_path, 'data-delimiter' => ',', :value => !!@ad_post.tags.include?(tag)


  .field 
    = form.file_field  :images, {id:"form_img", multiple: true, direct_uploads: true}

  .images__wrap
      -if @ad_post.images_filename?
          - @ad_post.images_filename.each  do |image|
            = cl_image_tag( image , :width => 100, :height => 100, :crop => :fill, class: "preview_image")
      
  .actions
    = form.submit
  
    
= javascript_include_tag 'preview'

app/views/ad_posts/edit.html.slim
h1 Editing Ad Post
= render 'form', ad_post: @ad_post
= link_to 'Show', @ad_post
| \
= link_to 'Back', ad_posts_path

app/views/ad_posts/index.html.slim
p#notice= notice
== pagy_bootstrap_nav(@pagy)
.wrapper 
    -@ad_posts.each do |ad_post|
      = link_to  ad_post ,:class => "ad_post-link" 
        .ad_post
          .ad_post__img_preview
              -if ad_post[:images_filename].nil?
                  .empty
                    span.empty_text No photo
              -else 
                  = cl_image_tag(ad_post[:images_filename].first , :width => 100, :height => 100, :crop => :fill)
          .ad_post__body
            h2.post_title= ad_post.title
            .post_description= ad_post.description
        

    
= link_to 'New Ad Post', new_ad_post_path


== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1 

app/views/ad_posts/new.html.slim
h1 New Ad Post
= render 'form', ad_post: @ad_post

= link_to 'Back', ad_posts_path

app/views/ad_posts/show.html.slim
p#notice= notice
p
  strong Title:
  = @ad_post.title
p
  strong Description:
  = @ad_post.description
p 
  strong Tags:
  - @tags.each do |tag|
    strong
      '  #
      =tag.title
      end
p 
  strong Images:
    -@ad_post.images_filename.each  do |image|
      = cl_image_tag( image , :width => 100, :height => 100, :crop => :fill)



= link_to 'Edit', edit_ad_post_path(@ad_post)
| \
= link_to 'Back', ad_posts_path

app/views/layouts/application.html.slim
doctype html
html lang ="en"
  head
    title= content_for?(:title) ? yield(:title) : "Untitled"
    meta content="text/html" 
    meta charset="UTF-8" http-equiv="Content-Type"   
    meta content="width=device-width, initial-scale=1.0" name="viewport" 
      = csrf_meta_tags
      = csp_meta_tag
      = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
      = stylesheet_link_tag 'normalize','jquery-ui', 'jquery-ui.min', 'jquery-ui.structure','jquery-ui.theme.min'   
      = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' 
      = javascript_include_tag 'jquery', 'rails', 'jquery-ui', 'jquery-ui.min.js', 'autocomplete-rails'
    link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" rel="stylesheet" /
    link href="navbar-top-fixed.css" rel="stylesheet" 
     = yield(:head)
    
  body
    header
        nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark.container-fluid
            a.navbar-brand href="/"  Twinslash ADS
            button.navbar-toggler aria-controls="navbarCollapse" aria-expanded="false" aria-label=("Toggle navigation") data-bs-target="#navbarCollapse" data-bs-toggle="collapse" type="button" 
            span.navbar-toggler-icon#navbarCollapse.collapse.navbar-collapse
            form.d-flex
                input.form-control.me-2 aria-label="Search" placeholder="Search" type="search" /
                button.btn.btn-outline-success type="submit"  Search
            ul.navbar-nav.me-auto.mb-2.mb-md-0
              li.nav-item
                a.nav-link.active aria-current="page" href="/ad_posts/new"  Add a new post
              li.nav-item
                a.nav-link href="/tags/new"  Add a new tag
              li.nav-item
              -if (user_signed_in?)
                a.nav-link href="/"  =current_user.name
              else
                a.nav-link href="/signup"  Sign up
              end

    main.container
        .bg-light.p-5.rounded
            = yield
body/

app/views/tags/_form.html.slim
= form_for @tag do |f|
  - if @tag.errors.any?
    #error_explanation
      h2 = "#{pluralize(@tag.errors.count, 'error')} prohibited this tag from being saved:"
      ul
        - @tag.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :tag
    = f.text_field :title
    
  = f.submit 

app/views/tags/edit.html.slim
h1 Editing tag

== render 'form'

=> link_to 'Show', @tag
'|
=< link_to 'Back', tags_path

app/views/tags/index.html.slim
h1 Listing tags

table
  thead
    tr
      th Tag
      th
      th
      th

  tbody
    - @tags.each do |tag|
      tr
        td = tag.title
        td = link_to 'Show', tag
        td = link_to 'Edit', edit_tag_path(tag)
        td = link_to 'Destroy', tag, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Tag', new_tag_path

app/views/tags/new.html.slim
h1 New tag

== render 'form'

= link_to 'Back', tags_path

app/views/tags/show.html.slim
p#notice = notice

p
  strong Tag:
  = @tag.title

=> link_to 'Edit', edit_tag_path(@tag)
'|
=< link_to 'Back', tags_path

app/views/users/_form.html.slim
= form_with(model: @user) do |f|
  - if @user.errors.any?
    #error_explanation
      h2
        = pluralize(@user.errors.count, "error")
        | prohibited this user from being saved:
      ul
        - user.errors.each do |error|
          li= error.full_message

  .field
    =f.label :email
  .field 
    =f.email_field :email, placeholder: "enter your e-mail"  
  .field
    =f.label :name
  .field
    =f.text_field :name, placeholder: "enter your name"
  .field 
    =f.label :password
  .field
    =f.password_field :password, placeholder: "password"
  .field 
    =f.label :password_confirmation
  .field
    =f.password_field :password_confirmation, placeholder: "password"

  .action
    =f.submit "Register!"   

app/views/users/new.html.slim
h1 Registration
== render 'form', user: @user
= link_to 'Back', root_path

app/views/welcome/show.html.slim
h1 Welcome#show
p Find me in app/views/welcome/show.html.slim